/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.EventQueue;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.xssf.usermodel.XSSFCell;

import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;

/**
 *
 * @author ac176227
 */
public class ViewGUI extends javax.swing.JFrame
{

    /**
     * Creates new form ViewGUI
     */
        public ViewGUI()
         {
            initComponents();
//             jtData.getSelectionModel().addListSelectionListener(new ListSelectionListener()
//             {
//                 @Override
//                 public void valueChanged(ListSelectionEvent event)
//                 {
//                     if (!jtData.getSelectionModel().isSelectionEmpty())
//                     {
//                         int selectedRow = jtData.getSelectionModel().getMinSelectionIndex();
//                         final JPanel panel = new JPanel();
//                         final JRadioButton button1 = new JRadioButton("pre-Calculus A");
//                         final JRadioButton button2 = new JRadioButton("pre-Calculus B");
//
//                         panel.add(button1);
//                         panel.add(button2);
//
//                         JOptionPane.showMessageDialog(null, panel);
//                         //JOptionPane.showMessageDialog(null, "Selected Row" + selectedRow);
//                     }
//                     //System.out.println(jtData.getValueAt(jtData.getSelectedRow(), 0).toString());
//                 }
//
//             });
                        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDialoge = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTable();
        panChooser = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        txtSearchBar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuImport = new javax.swing.JMenuItem();
        mnuCreateDataSheet = new javax.swing.JMenuItem();

        jDialoge.setMinimumSize(new java.awt.Dimension(400, 200));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogeLayout = new javax.swing.GroupLayout(jDialoge.getContentPane());
        jDialoge.getContentPane().setLayout(jDialogeLayout);
        jDialogeLayout.setHorizontalGroup(
            jDialogeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogeLayout.createSequentialGroup()
                .addContainerGap(752, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jDialogeLayout.setVerticalGroup(
            jDialogeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogeLayout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IB Sophomores dbs");
        setBackground(new java.awt.Color(219, 237, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jtData.setBackground(new java.awt.Color(204, 233, 247));
        jtData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID ", "Name"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jtData.getTableHeader().setReorderingAllowed(false);
        jtData.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jtDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtData);
        if (jtData.getColumnModel().getColumnCount() > 0)
        {
            jtData.getColumnModel().getColumn(0).setResizable(false);
            jtData.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout panChooserLayout = new javax.swing.GroupLayout(panChooser);
        panChooser.setLayout(panChooserLayout);
        panChooserLayout.setHorizontalGroup(
            panChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panChooserLayout.setVerticalGroup(
            panChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        lblTitle.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        lblTitle.setText("Incoming IB Sophomores");

        lblIcon.setIcon(new javax.swing.ImageIcon("H:\\Comp sci IA\\Webp.net-resizeimage.png")); // NOI18N
        lblIcon.setText("ib");

        txtSearchBar.setForeground(new java.awt.Color(0, 0, 0));
        txtSearchBar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtSearchBarKeyReleased(evt);
            }
        });

        jMenu1.setText("File");

        mnuImport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuImport.setText("Import File");
        mnuImport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuImportActionPerformed(evt);
            }
        });
        jMenu1.add(mnuImport);

        mnuCreateDataSheet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        mnuCreateDataSheet.setText("Create Data Sheet");
        mnuCreateDataSheet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuCreateDataSheetActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCreateDataSheet);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcon)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitle)
                        .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(panChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuImportActionPerformed
    {//GEN-HEADEREND:event_mnuImportActionPerformed
     JFileChooser chooser = new JFileChooser();
     FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel files", "xlsx");
     chooser.setFileFilter(filter);
     int returnVal = chooser.showOpenDialog(panChooser);
     if(returnVal == JFileChooser.APPROVE_OPTION)
     {
        try {
      
         String name;
         int IDNumber;
         XSSFWorkbook workbook = new XSSFWorkbook(new FileInputStream(chooser.getSelectedFile().getAbsolutePath()));
         XSSFSheet sheet = workbook.getSheetAt(0);  //this gets first sheet in workbook

         XSSFRow row;
         for(int r = 1; r < sheet.getLastRowNum()+1 ; r++)                 //rows start at 0, so do cells
         {
           row = sheet.getRow(r);
           name = row.getCell(0).getStringCellValue();   //assumes first cell is a String
           IDNumber = (int) row.getCell(1).getNumericCellValue();  //fourth cell is an int

           //System.out.printf("Name : %s\n", name);  //output what you read from excel
           //System.out.printf("ID : %d\n", IDNumber);
           //System.out.println();
          //following code connects table to excel file
           DefaultTableModel model = (DefaultTableModel) jtData.getModel();
           model.addRow(new Object [] {IDNumber, name});
      }
    } catch(IOException e){}
    }
    }//GEN-LAST:event_mnuImportActionPerformed

    private void mnuCreateDataSheetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuCreateDataSheetActionPerformed
    {//GEN-HEADEREND:event_mnuCreateDataSheetActionPerformed
     File file = new File("newfile.xlsx");
     JFileChooser chooser = new JFileChooser();
     FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel files", "xlsx");
     chooser.setFileFilter(filter);
     int returnVal = chooser.showOpenDialog(panChooser);
     if(returnVal == JFileChooser.APPROVE_OPTION)
        try
        {
          FileInputStream fis = new FileInputStream(new File(chooser.getSelectedFile().getAbsolutePath()));
		XSSFWorkbook workbook = new XSSFWorkbook (fis);
		XSSFSheet sheet = workbook.getSheetAt(0);
                
		/*------------------
                  Creates First Row
                --------------------*/
                
                //English
		XSSFRow row1 = sheet.createRow(0);
		XSSFCell r1c1 = row1.createCell(2);
		r1c1.setCellValue("ENG 1A");
		XSSFCell r1c2 = row1.createCell(3);
		r1c2.setCellValue("ENG 1B");
		XSSFCell r1c3 = row1.createCell(4);
		r1c3.setCellValue("ENG 2A");
                XSSFCell r1c4 = row1.createCell(5);
		r1c4.setCellValue("ENG 2B");
                XSSFCell r1c5 = row1.createCell(6);
		r1c5.setCellValue("ENG 3A");
                XSSFCell r1c6 = row1.createCell(7);
		r1c6.setCellValue("ENG 3B");
                XSSFCell r1c7 = row1.createCell(8);
		r1c7.setCellValue("ENG 4A");
                XSSFCell r1c8 = row1.createCell(9);
		r1c8.setCellValue("ENG 4B");
                
                //Math 
                XSSFCell r1c9 = row1.createCell(10);
		r1c9.setCellValue("ALG A");
                XSSFCell r1c10 = row1.createCell(11);
		r1c10.setCellValue("ALG B");
                XSSFCell r1c11= row1.createCell(12);
		r1c11.setCellValue("GEOM A");
                XSSFCell r1c12= row1.createCell(13);
		r1c12.setCellValue("GEOM B");
                XSSFCell r1c13 = row1.createCell(14);
		r1c13.setCellValue("ALG2 A");
                XSSFCell r1c14 = row1.createCell(15);
		r1c14.setCellValue("ALG2 B");
                XSSFCell r1c15 = row1.createCell(16);
		r1c15.setCellValue("SLMATH A");
                XSSFCell r1c16 = row1.createCell(17);
		r1c16.setCellValue("SLMATH B");
                XSSFCell r1c17 = row1.createCell(18);
		r1c17.setCellValue("HLMATCH A");
                XSSFCell r1c18 = row1.createCell(19);
		r1c18.setCellValue("HLMATH B");
                XSSFCell r1c19 = row1.createCell(20);
		r1c19.setCellValue("HLMATH C");
                
                //Science 
                XSSFCell r1c20 = row1.createCell(21);
		r1c20.setCellValue("BIO A");
                XSSFCell r1c21 = row1.createCell(22);
		r1c21.setCellValue("BIO B");
                XSSFCell r1c22 = row1.createCell(23);
		r1c22.setCellValue("CHEM A");
                XSSFCell r1c23 = row1.createCell(24);
		r1c23.setCellValue("CHEM B");
                XSSFCell r1c24 = row1.createCell(25);
		r1c24.setCellValue("SCI3 A");
                XSSFCell r1c25 = row1.createCell(26);
		r1c25.setCellValue("SCI3 B");
                XSSFCell r1c26 = row1.createCell(27);
		r1c26.setCellValue("SCI3 C");
                XSSFCell r1c27 = row1.createCell(28);
		r1c27.setCellValue("SCI4 A");
                XSSFCell r1c28 = row1.createCell(29);
		r1c28.setCellValue("SCI4 B");
                XSSFCell r1c29 = row1.createCell(30);
		r1c29.setCellValue("SCI4 C");
                
                //Social Studies
                XSSFCell r1c30 = row1.createCell(31);
                r1c30.setCellValue("WORLD GEO A");
                XSSFCell r1c31 = row1.createCell(32);
                r1c31.setCellValue("WORLD GEO B");
                XSSFCell r1c32 = row1.createCell(33);
                r1c32.setCellValue("WORLD HIST A");
                XSSFCell r1c33 = row1.createCell(34);
                r1c33.setCellValue("WORLD HIST B");
                XSSFCell r1c34 = row1.createCell(35);
                r1c34.setCellValue("HOA A");
                XSSFCell r1c35 = row1.createCell(36);
                r1c35.setCellValue("HOA B");
                XSSFCell r1c36 = row1.createCell(37);
                r1c36.setCellValue("2OTH CENTURY A");
                XSSFCell r1c37 = row1.createCell(38);
                r1c37.setCellValue("20TH CENTURY B");
                XSSFCell r1c38 = row1.createCell(39);
                r1c38.setCellValue("ECON AP/IB/DUAL");
                
                //Health
                XSSFCell r1c39 = row1.createCell(40);
                r1c39.setCellValue("HEALTH");
                XSSFCell r1c40 = row1.createCell(41);
                r1c40.setCellValue("HUM SERVICE A");
                XSSFCell r1c41 = row1.createCell(42);
                r1c41.setCellValue("HUM SERVICE B");
                XSSFCell r1c42 = row1.createCell(43);
                r1c42.setCellValue("HLTH SCIENCE A");
                XSSFCell r1c43 = row1.createCell(44);
                r1c43.setCellValue("HLTH SCIENCE B");
                XSSFCell r1c44 = row1.createCell(45);
                r1c44.setCellValue("COSMO1 A");
                XSSFCell r1c45 = row1.createCell(46);
                r1c45.setCellValue("COSMO1 B");
                XSSFCell r1c46 = row1.createCell(47);
                r1c46.setCellValue("COSMO1 C");
                XSSFCell r1c47 = row1.createCell(48);
                r1c47.setCellValue("COUN/MEN HLTH A");
                XSSFCell r1c48 = row1.createCell(49);
                r1c48.setCellValue("COUN/MEN HLTH B");
                
                //PE/Athletics
                XSSFCell r1c49 = row1.createCell(50);
                r1c49.setCellValue("PE/ATHLT A");
                XSSFCell r1c50 = row1.createCell(51);
                r1c50.setCellValue("PE/ATHLT B");
                
                //Technology
                XSSFCell r1c51 = row1.createCell(52);
                r1c51.setCellValue("TECH A");
                XSSFCell r1c52 = row1.createCell(53);
                r1c52.setCellValue("TECH B");
                
                //Fine Arts
                XSSFCell r1c53 = row1.createCell(54);
                r1c53.setCellValue("ART A");
                XSSFCell r1c54 = row1.createCell(55);
                r1c54.setCellValue("ART B");
                XSSFCell r1c55 = row1.createCell(56);
                r1c55.setCellValue("BAND A");
                XSSFCell r1c56 = row1.createCell(57);
                r1c56.setCellValue("BAND B");
                XSSFCell r1c57 = row1.createCell(58);
                r1c57.setCellValue("CHOIR A");
                XSSFCell r1c58 = row1.createCell(59);
                r1c58.setCellValue("CHOIR B");
                XSSFCell r1c59 = row1.createCell(60);
                r1c59.setCellValue("DANCE A");
                XSSFCell r1c60 = row1.createCell(61);
                r1c60.setCellValue("DANCE B");
                XSSFCell r1c61 = row1.createCell(62);
                r1c61.setCellValue("ORCH A");
                XSSFCell r1c62 = row1.createCell(63);
                r1c62.setCellValue("ORCH B");
                XSSFCell r1c63 = row1.createCell(64);
                r1c63.setCellValue("THEATER A");
                XSSFCell r1c64 = row1.createCell(65);
                r1c64.setCellValue("THEATER B");
                
                //World Languages
                XSSFCell r1c65 = row1.createCell(66);
                r1c65.setCellValue("LANG1 A");
                XSSFCell r1c66 = row1.createCell(67);
                r1c66.setCellValue("LANG1 B");
                XSSFCell r1c67 = row1.createCell(68);
                r1c67.setCellValue("LANG2 A");
                XSSFCell r1c68 = row1.createCell(69);
                r1c68.setCellValue("LANG2 B");
                
                //Speech
                XSSFCell r1c69 = row1.createCell(70);
                r1c69.setCellValue("PROF COMM");
                
                //TOK (Theory of Knowledge)
                XSSFCell r1c70 = row1.createCell(71);
                r1c70.setCellValue("TOK A");
                XSSFCell r1c71 = row1.createCell(72);
                r1c71.setCellValue("TOK B");
                
		fis.close();
		FileOutputStream fos =new FileOutputStream(new File("newfile.xlsx"));
	        workbook.write(fos);
	        fos.close();
		System.out.println("Done");
            
        } catch(IOException e){
                System.out.println(e);
                }
    }//GEN-LAST:event_mnuCreateDataSheetActionPerformed

    private void filter(String query)
    {
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> ((DefaultTableModel) jtData.getModel());
      jtData.setRowSorter(tr); 
      tr.setRowFilter(RowFilter.regexFilter("(?i)"+query));
    }
    
    private void txtSearchBarKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtSearchBarKeyReleased
    {//GEN-HEADEREND:event_txtSearchBarKeyReleased
        String query = txtSearchBar.getText();
        filter(query); 
    }//GEN-LAST:event_txtSearchBarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        jDialoge.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtDataMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jtDataMouseClicked
    {//GEN-HEADEREND:event_jtDataMouseClicked
        jDialoge.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jtDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ViewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialoge;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtData;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem mnuCreateDataSheet;
    private javax.swing.JMenuItem mnuImport;
    private javax.swing.JPanel panChooser;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
